oauth2:
  host: http://localhost:3210
  path: /api/v1/example/oauth/token
  clientId: 123456
  clientSecret: 654321
leads:
  host: http://localhost:3210
  path: /api/v1/example/get
  apiId: acbasdj
  dtini: 01/08/2021
  dtFim: 30/11/2021
  indicador: FULANO
csv:
  prefix: RelatorioRequisicao
  dtformat: yyyyMMdd_HHmmss
  append: true
batch:
  qtdeTasks: 5
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
logging:
  level:
    - br.com.kazuo.leadsbatch.dataprovider.feign.leads: DEBUG
    - br.com.kazuo.leadsbatch.dataprovider.feign.oauth2: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true